name = "veraverde-website"
compatibility_date = "2025-01-25"
pages_build_output_dir = ".output/public"

[build]
command = "pnpm run build"

[build.environment_variables]
NODE_VERSION = "18.17.0"
NITRO_PRESET = "cloudflare-pages"